# 📱 Planner App - แอปจัดการงานและปฏิทิน
name: plannerapp
description: "A Flutter project for managing projects and calendar events."

version: 1.0.0+1

# กำหนดเวอร์ชัน Dart SDK ที่ใช้
environment:
  sdk: ^3.9.2

# 📦 Dependencies - Packages ที่ใช้ในแอป
dependencies:
  # Flutter framework
  flutter:
    sdk: flutter
  
  # Icons สำหรับ UI
  cupertino_icons: ^1.0.8
  
  # ปฏิทิน
  table_calendar: ^3.1.2
  
  # จัดการไฟล์และโฟลเดอร์
  path_provider: ^2.1.3
  path: ^1.9.0
  
  # ฐานข้อมูล SQLite
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3+1
  
  # เก็บข้อมูลการตั้งค่า
  shared_preferences: ^2.2.2

# 🧪 Development Dependencies - สำหรับการพัฒนา
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# 🎨 Flutter Configuration
flutter:
  # ไฟล์ข้อมูลที่ใช้ในแอป
  assets:
    - assets/events.json
    - assets/important_days.json
    - assets/ku_calendar.json
  
  # ใช้ Material Design
  uses-material-design: true
